spring.application.name=my-first-project

spring.security.user.name=sahel
spring.security.user.password=test
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.jpa.defer-datasource-initialization=true
